apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - servicemonitor-istiod.yaml
  - servicemonitor-ingressgateway.yaml
  - servicemonitor-envoy-stats.yaml

commonLabels:
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: istio
