apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/manubalasree/url-shortener-sre-lab
    targetRevision: main
    path: kubernetes/kustomize/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: databases.spotahome.com
    kind: RedisFailover
    jqPathExpressions:
    - .status
