apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: shlink
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: postgres-secret-store
    kind: SecretStore
  target:
    name: shlink-db-pguser-shlink
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: shlink-db-pguser-shlink
      property: password
  - secretKey: user
    remoteRef:
      key: shlink-db-pguser-shlink
      property: user
  - secretKey: dbname
    remoteRef:
      key: shlink-db-pguser-shlink
      property: dbname
  - secretKey: host
    remoteRef:
      key: shlink-db-pguser-shlink
      property: host
  - secretKey: port
    remoteRef:
      key: shlink-db-pguser-shlink
      property: port
