apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shlink

resources:
- deployment.yaml
- service.yaml
- secret-store.yaml
- external-secret.yaml
- istio/gateway.yaml
- istio/virtualservice.yaml
