apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: shlink
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: postgres
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["shlink-db-pguser-shlink"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-reader
  namespace: postgres
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: shlink
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: postgres-secret-store
  namespace: shlink
spec:
  provider:
    kubernetes:
      remoteNamespace: postgres
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-sa
