apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - telemetry.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/component: telemetry
  app.kubernetes.io/part-of: istio
