apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis

secretGenerator:
- name: redis-password
  literals:
  - password=shlinkRedis2024!

generatorOptions:
  disableNameSuffixHash: true
