apiVersion: v1
kind: Service
metadata:
  name: rfr-shlink-redis
  namespace: redis
  labels:
    app.kubernetes.io/component: redis
    redisfailovers.databases.spotahome.com/name: shlink-redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app.kubernetes.io/component: redis
    redisfailovers.databases.spotahome.com/name: shlink-redis
  type: ClusterIP
