apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: shlink-virtualservice
  namespace: shlink
spec:
  hosts:
  - "*"
  gateways:
  - shlink-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: shlink.shlink.svc.cluster.local
        port:
          number: 8080
