# Kiali Operator Helm values
cr:
  create: true
  name: kiali
  namespace: observability
  spec:
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces:
      - '**'
      service_type: LoadBalancer
    external_services:
      prometheus:
        url: http://prometheus-stack-kube-prom-prometheus.observability:9090
      grafana:
        enabled: true
        in_cluster_url: http://prometheus-stack-grafana.observability:80
        url: http://prometheus-stack-grafana.observability:80
      tracing:
        enabled: true
        in_cluster_url: http://jaeger-query.observability:16686
        url: http://jaeger-query.observability:16686
        use_grpc: false
